### Create a new User

POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "1234567"
}

### Login the user

POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "1234567"
}

### Get the singed in user details
GET http://localhost:3000/auth/whoami

### Sign out
POST http://localhost:3000/auth/signout

### Find a user with id
GET http://localhost:3000/auth/3


### Find the user with email
GET http://localhost:3000/auth?email=unique@gmail.com


### Delete the user with id
DELETE http://localhost:3000/auth/2

### Update user with given id
PATCH http://localhost:3000/auth/3
Content-Type: application/json

{
    "email": "howdy@howdymail.com",
    "password": "passwody"
}
